### <------------------- Items ------------------->

### Register Bread item
POST http://localhost:8081/item
Content-Type: application/json

{
  "name": "Bread",
  "price": 2.5,
  "type": "BAKERY"
}

### Register Croissant item
POST http://localhost:8081/item
Content-Type: application/json

{
  "name": "Croissant",
  "price": 0.99,
  "type": "BAKERY"
}


### Register Cola item
POST http://localhost:8081/item
Content-Type: application/json

{
  "name": "Cola",
  "price": 3.5,
  "type": "DRINKS"
}


### Get all the items
GET http://localhost:8081/

### Get the item by its id
GET http://localhost:8081/{{id}}

### <------------------- Orders ------------------->

### Register a new order
POST http://localhost:8081/orders
Content-Type: application/json

{
  "itemId": "5da473c1-4cd1-4adf-a2f0-73f8f2b22c1f",
  "price": "3.5",
  "amount": 2
}

### Get all the orders
GET http://localhost:8081/orders

### Get Order by ID
@id = 0bbecc3a-22dc-4f05-a0d1-640916337b15
GET localhost:8081/orders/{{id}}